name: pigemshubshop
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  json_annotation: ^4.8.1
  json_serializable: ^6.7.0

  # Firebase Plugin
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2
  firebase_remote_config: ^4.2.3
  firebase_app_check: ^0.1.5
  firebase_crashlytics: ^3.3.3
  firebase_analytics: ^10.4.3
  firebase_messaging: ^14.6.4

  #local notifications
  flutter_local_notifications: ^15.1.0+1

  # Service Locator
  get_it: ^7.6.0

  # Generate Launcher Icon
  flutter_launcher_icons: ^0.13.1

  # To handle SVG images
  flutter_svg: ^2.0.6

  # Font
  google_fonts: ^4.0.3

  # Provider (State management)
  provider: ^6.0.5

  #Platform id
#  platform_device_id: ^1.0.1

  # Provides internationalization and localization facilities
  intl: ^0.18.1

  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.8.8

  # Converts a date into a humanized text
  timeago: ^3.4.0

  # Local Storage
  shared_preferences: ^2.1.2

  # Url Launcher
  url_launcher: ^6.1.11

  # Badges
  badges: ^3.1.1

  # Equatable to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

  # Handle Image Compress
  flutter_image_compress: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  build_runner: ^2.4.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/launcher_icons/
    - assets/images/
